services:
  db:
    image: postgres:16
    container_name: postgres-bank
    environment:
      POSTGRES_DB: banktdah
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 971325
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - banking_cpp_banknet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s

  app:
    build: .
    container_name: bank-system
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: postgres-bank
      PGUSER: postgres
      PGPASSWORD: 971325
      PGDATABASE: banktdah
    networks:
      - banking_cpp_banknet
    entrypoint: ["./bin/bank_app"]

networks:
  banking_cpp_banknet:
    driver: bridge
volumes:
  postgres_data:
